# Generated by ChatGPT - initial migration for Order model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(help_text="External facing order identifier", max_length=64, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("created", "Created"), ("delivered", "Delivered"), ("invoiced", "Invoiced")], default="created", help_text="Lifecycle status of the order", max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
